import { 
  Announcement, 
  Session, 
  LeaderboardEntry, 
  SessionRequest, 
  AdminStats, 
  GlobalStudent, 
  GlobalTeacher 
} from './types';

export const initialAnnouncements: Announcement[] = [
  { 
    id: '1', 
    text: 'نرحب بجميع الطالبات الجدد في نادي مسك للفصل الدراسي الحالي.', 
    type: 'text', 
    date: '2026-06-04', 
    author: 'الإدارة' 
  },
  { 
    id: '2', 
    text: 'فتح باب طلبات الانضمام للحِلق للجميع (طالبات وإداريات).', 
    type: 'text', 
    date: '2026-06-03', 
    author: 'الإدارة' 
  }
];

export const initialSessions: Session[] = [
  { 
    id: '1', 
    name: 'حلقة صفوة الإتقان', 
    themeColor: '#7C3AED', // Royal Purple
    themePhoto: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=600',
    teacher: {
      name: 'أ. مريم الهنائية', 
      phone: '+968 9111 2233'
    },
    location: 'مركز الطلاب - قاعة 102',
    time: 'الأحد والثلاثاء | 16:00 - 18:00', 
    maxStudents: 15, 
    level: 'ADVANCED',
    students: [
      { id: 's1', name: 'أمل الفارسية', money: 2850, avatar: 'https://picsum.photos/seed/s1/100/100', absencesExcused: 1, absencesUnexcused: 0, email: 'amel@student.squ.edu.om', phone: '+968 9776 5544', college: 'التربية', cohort: '2022' },
      { id: 's2', name: 'زكية الهاشمية', money: 1200, avatar: 'https://picsum.photos/seed/s2/100/100', absencesExcused: 0, absencesUnexcused: 1, email: 'zakia@student.squ.edu.om', phone: '+968 9112 3344', college: 'التربية', cohort: '2023' },
      { id: 's3', name: 'بسمة الراشدية', money: 950, avatar: 'https://picsum.photos/seed/s3/100/100', absencesExcused: 2, absencesUnexcused: 0, email: 'basma@student.squ.edu.om', phone: '+968 9554 3322', college: 'التربية', cohort: '2022' }
    ],
    announcements: [
      { 
        id: 'sa1', 
        text: 'مرحبا بكن في حلقتنا المتميزة. يرجى مراجعة أحكام النون الساكنة والتنوين.', 
        type: 'text',
        date: '2026-06-04',
        author: 'مريم الهنائية'
      },
      { 
        id: 'sa2', 
        text: 'تحققوا من هذا المقطع التعليمي حول مخارج الحروف لتصحيح النطق وتجويد الأداء.', 
        type: 'video',
        attachment: 'https://www.youtube.com/embed/placeholder',
        date: '2026-06-03',
        author: 'مريم الهنائية'
      },
      {
        id: 'sa3',
        text: 'تصويت: ما هو الوقت المفضل للحصة الإضافية الأسبوع القادم؟',
        type: 'poll',
        pollOptions: [
          { id: 1, text: 'الخميس 4 عصراً', votes: 12 },
          { id: 2, text: 'الجمعة 10 صباحاً', votes: 8 }
        ],
        date: '2026-06-02',
        author: 'مريم الهنائية'
      }
    ]
  },
  { 
    id: '2', 
    name: 'أساسيات الترتيل القرآني', 
    themeColor: '#059669', // Emerald Green
    themePhoto: 'https://images.unsplash.com/photo-1564121211835-e88c852648ab?auto=format&fit=crop&q=80&w=600',
    teacher: {
      name: 'أ. عائشة الشكيلية', 
      phone: '+968 9222 3344'
    },
    location: 'مسجد الجامعة - الدور 1',
    time: 'الاثنين والأربعاء | 10:00 - 12:00', 
    maxStudents: 10, 
    level: 'BEGINNER',
    students: [
      { id: 's4', name: 'عائشة الهنائية', money: 450, avatar: 'https://picsum.photos/seed/s4/100/100', absencesExcused: 1, absencesUnexcused: 0, email: 'aisha@student.squ.edu.om', phone: '+968 7766 5544', college: 'التربية', cohort: '2022' },
      { id: 's5', name: 'سارة الجابرية', money: 800, avatar: 'https://picsum.photos/seed/s5/100/100', absencesExcused: 0, absencesUnexcused: 0, email: 'sara@student.squ.edu.om', phone: '+968 9345 6789', college: 'العلوم', cohort: '2024' }
    ],
    announcements: [
      { 
        id: 'sa4', 
        text: 'أهلاً بطالبات أساسيات الترتيل، الحصة القادمة سنركز على موازين المدود الحركية.', 
        type: 'text',
        date: '2026-06-04',
        author: 'عائشة الشكيلية'
      }
    ]
  },
  { 
    id: '3', 
    name: 'حلقة مخارج الحروف وصفاتها (مكتملة - خريف ٢٠٢٥)', 
    themeColor: '#D97706', // Warm Amber/Ochre
    themePhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600',
    isPast: true,
    teacher: {
      name: 'أ. وفاء الندابية', 
      phone: '+968 9444 5566'
    },
    location: 'عبر الأثير - تيمز',
    time: 'السبت | 09:00 - 11:00', 
    maxStudents: 20, 
    level: 'BEGINNER',
    students: [
      { id: 's4', name: 'عائشة الهنائية', money: 450, avatar: 'https://picsum.photos/seed/s4/100/100', absencesExcused: 1, absencesUnexcused: 0, email: 'aisha@student.squ.edu.om', phone: '+968 7766 5544', college: 'التربية', cohort: '2022' },
      { id: 's1', name: 'أمل الفارسية', money: 2850, avatar: 'https://picsum.photos/seed/s1/100/100', absencesExcused: 1, absencesUnexcused: 0, email: 'amel@student.squ.edu.om', phone: '+968 9776 5544', college: 'التربية', cohort: '2022' }
    ],
    announcements: [
      { 
        id: 'sa5', 
        text: 'أتممنا بفضل الله وكرمه منهاج مخارج الحروف، طوبى لمن اجتهدت وثابرت.', 
        type: 'text',
        date: '2025-12-15',
        author: 'وفاء الندابية'
      }
    ]
  }
];

export const initialLeaderboard: LeaderboardEntry[] = [
  { id: 'u1', name: 'أمل الفارسية', money: 2850, rank: 1, avatar: 'https://picsum.photos/seed/l1/100/100' },
  { id: 'u2', name: 'سناء العبرية', money: 2600, rank: 2, avatar: 'https://picsum.photos/seed/l2/100/100' },
  { id: 'u3', name: 'هند البلوشية', money: 2450, rank: 3, avatar: 'https://picsum.photos/seed/l3/100/100' },
  { id: 'u4', name: 'وفاء الندابية', money: 2100, rank: 4, avatar: 'https://picsum.photos/seed/l4/100/100' },
  { id: 'u5', name: 'منال الشعيبية', money: 1950, rank: 5, avatar: 'https://picsum.photos/seed/l5/100/100' }
];

export const initialSessionRequests: SessionRequest[] = [
  { id: 'r1', name: 'منى الراشدية', level: 'BEGINNER', date: '2026-06-04' },
  { id: 'r2', name: 'فاطمة العلوية', level: 'ADVANCED', date: '2026-06-03' }
];

export const initialAdminStats: AdminStats = {
  totalStudents: 145,
  totalTeachers: 12,
  totalSessions: 10,
  pendingRequests: 2
};

export const initialAllStudents: GlobalStudent[] = [
  { name: 'أمل الفارسية', phone: '96877665544', level: 'ADVANCED', session: 'حلقة النور', info: 'مجتهدة جداً' },
  { name: 'زكية الهاشمية', phone: '96811223344', level: 'BEGINNER', session: 'حلقة النور', info: 'تحسن ملحوظ في التلاوة الحركية' },
  { name: 'بسمة الراشدية', phone: '96855443322', level: 'INTERMEDIATE', session: 'حلقة النور', info: 'التزام تام بالحضور والمراجعة' },
  { name: 'فاطمة العلوية', phone: '96899887766', level: 'BEGINNER', session: 'Pending', info: 'بانتظار التوزيع على الحلقات المفتوحة' }
];

export const initialAllTeachers: GlobalTeacher[] = [
  { name: 'مريم الهنائية', phone: '96812345678', level: 'Master', session: 'حلقة النور', info: 'خبيرة ومجازة في التلاوة والقراءات العشر' },
  { name: 'سارة البلوشية', phone: '96887654321', level: 'Advanced', session: 'حلقة التميز', info: 'متخصصة في أحكام التجويد ومخارج الحروف' }
];

export const translations = {
  en: {
    title: "Misk",
    login: "Sign In",
    register: "Register Now",
    welcomeBack: "Welcome Back",
    signInAccount: "Sign in to your account",
    email: "Email Address",
    password: "Password",
    about: "About",
    heroTitle: "Misk",
    heroSubtitle: "Indeed, those who recite the Book of Allah and establish prayer and spend out of what We have provided them, secretly and publicly, expect a profit that will never perish.",
    getStarted: "Get Started",
    contact: "Contact Us",
    terms: "Terms",
    logout: "Logout",
    profile: "Profile",
    dashboard: "Dashboard",
    controlPanel: "Control Panel",
    mySession: "My Session",
    currentSession: "My Session",
    announcements: "Announcements",
    sessions: "Sessions",
    requests: "Join Requests",
    overview: "Overview",
    save: "Save",
    firstName: "First Name",
    lastName: "Last Name",
    fatherName: "Father's Name",
    phoneNumber: "Phone Number",
    college: "College",
    cohort: "Cohort",
    academicYear: "Academic Year",
    studentId: "Student ID",
    academicDegree: "Academic Degree",
    accommodation: "Accommodation",
    onCampus: "On Campus",
    offCampus: "Off Campus",
    studentCard: "Student Card Photo",
    regNow: "Register",
    backHome: "Back to Home",
    success: "Registered Successfully!",
    submissionNote: "Your application is under review. You will be notified via email once approved.",
    teacher: "Teacher",
    student: "Student",
    admin: "Administrator",
    level: "Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    preIqraa: "Pre-Iqraa",
    firstTime: "First Time",
    iqraaStudent: "Iqraa Student",
    certified: "Certified",
    levelLabel: "Level",
    xpLabel: "XP",
    rankLabel: "Rank",
    progressLabel: "Progress to Next Level",
    guildMembers: "Guild Members",
    viewGuild: "View Guild",
    achievements: "Achievements",
    streak: "Day Streak",
    mastery: "Mastery",
    coach: "Coach / Teacher",
    leaderboard: "Top Earners Leaderboard",
    sessionLeaderboard: "Class Ranking",
    money: "Cash Collected",
    rank: "Rank",
    enrollRequest: "Session Registration Request",
    enrollSubtitle: "Apply to join a recitation session for this semester.",
    applyNow: "Submit Request",
    sessionLocation: "Session Location",
    sessionName: "Session Name",
    sessionPhone: "Teacher Contact",
    updateInfo: "Update Session Settings",
    awardMoney: "Send Gift",
    giveMoney: "Give Money",
    giftMsgPlaceholder: "Write an encouraging message...",
    message: "Encouraging Message",
    studentList: "Students List",
    absencesExcused: "Absences (Excused)",
    absencesUnexcused: "Absences (Unexcused)",
    totalCash: "Total Cash",
    semesterBalance: "Semester Balance",
    receivedGift: "You've received a gift!",
    noAccount: "Don't have an account?",
    teacherAnnouncements: "Teacher Announcements",
    postAnnouncement: "Post Announcement",
    attachment: "Attachment",
    addLink: "Add Link",
    addMedia: "Add Media",
    createPoll: "Create Poll",
    adminControlPanel: "Admin Control Panel",
    manageRequests: "Manage Requests",
    totalSessions: "Total Sessions",
    teacherList: "Teachers List",
    contactNumber: "Contact Number",
    importantInfo: "Important Info",
    notAssigned: "Not Assigned",
    backToPanel: "Back to Control Panel",
    editProfile: "Edit User Profile",
    degreeMaster: "Master",
    degreePhD: "PhD",
    degreeEmployee: "Employee",
    degreeBachelor: "Bachelor",
    senior: "Senior / Graduate",
    yes: "Yes",
    no: "No",
    systemStats: "System Statistics",
    examResults: "Exam Results",
    theoryExam: "Theory Exam",
    practicalExam: "Practical Exam",
    theoryScoreInfo: "Passing grade is 20",
    passMessage: "Congratulations! You have successfully passed the level requirements.",
    failMessage: "We wish you better luck next time. You haven't passed the level requirements yet.",
    grade: "Grade",
    status: "Status",
    pass: "Passed",
    fail: "Not Passed",
    practicalEvalInfo: "Notes: focus on ghunnah duration, vowel accuracy, tafkhim and tarqiq rules",
    viewResults: "View Results",
    examResultsBody: "Your end-of-semester results are now available. Check your status!",
    approve: "Approve",
    reject: "Reject",
    pollVote: "Vote",
    pollVoted: "You voted",
    totalVotes: "votes",
    registered: "Registered",
    notRegistered: "Not Registered",
    contactTitle: "Contact Us",
    contactSubtitle: "Reach out to us via WhatsApp or Email",
    contactWhatsApp: "WhatsApp Support",
    contactEmail: "Email Us",
    conditionsTitle: "Participation Conditions",
    conditionsContent: [
      "Maintain regular attendance in sessions.",
      "Follow the club's code of conduct and student guidelines.",
      "Complete assigned Quranic recitation tasks on time.",
      "Participate in club activities and events actively."
    ],
    aboutContent: "Misk is one of the student clubs at Sultan Qaboos University, supervised by the Deanship of Student Affairs. It aims to prepare a generation that recites the Quran efficiently and masters its rules through specialized educational programs.",
  },
  ar: {
    title: "مسك",
    login: "تسجيل الدخول",
    register: "سجل الآن",
    welcomeBack: "مرحباً بك مجدداً",
    signInAccount: "قم بتسجيل الدخول إلى حسابك",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    about: "حول",
    heroTitle: "مسك",
    heroSubtitle: "إِنَّ الَّذِينَ يَتْلُونَ كِتَابَ اللَّهِ وَأَقَامُوا الصَّلَاةَ وَأَنفَقُوا مِمَّا رَزَقْنَاهُمْ سِرًّا وَعَلَانِيَةً يَرْجُونَ تِجَارَةً لَّن تَبُورَ",
    getStarted: "ابدأ الآن",
    contact: "اتصل بنا",
    terms: "الشروط",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    dashboard: "لوحة التحكم",
    controlPanel: "لوحة التحكم",
    mySession: "حلقتي",
    currentSession: "حلقتي",
    announcements: "الإعلانات",
    sessions: "الحلقات",
    requests: "طلبات الانضمام",
    overview: "نظرة عامة",
    save: "حفظ",
    firstName: "الاسم",
    lastName: "اللقب",
    fatherName: "اسم الأب",
    phoneNumber: "رقم الهاتف",
    college: "الكلية",
    cohort: "الدفعة",
    academicYear: "السنة الأكاديمية",
    studentId: "الرقم الجامعي",
    academicDegree: "الدرجة العلمية",
    accommodation: "السكن",
    onCampus: "داخل مجمع سكني",
    offCampus: "خارج مجمع سكني",
    studentCard: "صورة البطاقة الجامعية",
    regNow: "سجل الآن",
    backHome: "العودة للرئيسية",
    success: "تم التسجيل بنجاح!",
    submissionNote: "طلبك قيد المراجعة حالياً. سيتم إخطارك عبر البريد الإلكتروني فور الموافقة عليه.",
    teacher: "معلم",
    student: "طالب",
    admin: "مسؤول",
    level: "المستوى",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    preIqraa: "قبل تمكين",
    firstTime: "أول مرة",
    iqraaStudent: "طالب إقراء",
    certified: "مجاز",
    levelLabel: "المستوى",
    xpLabel: "نقاط الخبرة",
    rankLabel: "الرتبة",
    progressLabel: "التقدم للمستوى التالي",
    guildMembers: "أعضاء الحلقة (الفريق)",
    viewGuild: "عرض الفريق",
    achievements: "الإنجازات",
    streak: "أيام متتالية",
    mastery: "إتقان",
    coach: "المدربة / المعلمة",
    leaderboard: "لوحة المتصدرين (الأعلى جمعاً)",
    sessionLeaderboard: "ترتيب الحلقة",
    money: "المبالغ المجموعة",
    rank: "الرتبة",
    enrollRequest: "طلب تسجيل في حلقة",
    enrollSubtitle: "قدم طلباً للانضمام إلى حلقة تلاوة لهذا الفصل.",
    applyNow: "تقديم الطلب",
    sessionLocation: "موقع الحلقة",
    sessionName: "اسم الحلقة",
    sessionPhone: "رقم تواصل المعلمة",
    updateInfo: "تحديث معلومات الحلقة",
    awardMoney: "إرسال هدية مالية",
    giveMoney: "منح مكافأة",
    giftMsgPlaceholder: "اكتب رسالة تشجيعية هنا...",
    message: "الرسالة التشجيعية",
    studentList: "قائمة الطالبات",
    absencesExcused: "غياب (بعذر)",
    absencesUnexcused: "غياب (بدون عذر)",
    totalCash: "إجمالي المبلغ",
    semesterBalance: "رصيد الفصل",
    receivedGift: "لقد حصلتِ على هدية!",
    noAccount: "ليس لديك حساب؟",
    teacherAnnouncements: "إعلانات المعلمة",
    postAnnouncement: "نشر إعلان جديد",
    attachment: "مرفق",
    addLink: "إضافة رابط",
    addMedia: "إضافة وسائط",
    createPoll: "إنشاء تصويت",
    adminControlPanel: "لوحة تحكم المسؤول",
    manageRequests: "إدارة الطلبات",
    totalSessions: "إجمالي الحلقات",
    teacherList: "قائمة المعلمات",
    contactNumber: "رقم التواصل",
    importantInfo: "معلومات هامة",
    notAssigned: "غير موزعة",
    backToPanel: "العودة للوحة التحكم",
    editProfile: "تعديل ملف المستخدم",
    degreeMaster: "ماجستير",
    degreePhD: "دكتوراة",
    degreeEmployee: "موظفة",
    degreeBachelor: "بكالوريوس",
    senior: "خريجة / موظفة",
    yes: "نعم",
    no: "لا",
    systemStats: "إحصائيات النظام",
    examResults: "نتائج الاختبارات",
    theoryExam: "الاختبار النظري",
    practicalExam: "الاختبار العملي",
    theoryScoreInfo: "درجة النجاح هي 20",
    passMessage: "تهانينا! لقد اجتزتِ متطلبات القبول لهذا المستوى بنجاح.",
    failMessage: "حظاً أوفر في المرة القادمة. لم يتم اجتياز متطلبات المستوى بعد.",
    grade: "الدرجة",
    status: "الحالة",
    pass: "ناجحة",
    fail: "لم تجتاز",
    practicalEvalInfo: "الملاحظات: اسقاط غنة, احكام الحركات, التفخيم والترقيق",
    viewResults: "عرض النتائج",
    examResultsBody: "نتائج نهاية الفصل الدراسي متاحة الآن. تحققي من حالتك!",
    approve: "موافقة",
    reject: "رفض",
    pollVote: "تصويت",
    pollVoted: "لقد صوّت",
    totalVotes: "أصوات",
    registered: "مسجلة",
    notRegistered: "غير مسجلة",
    contactTitle: "تواصل معنا",
    contactSubtitle: "يمكنك التواصل معنا عبر الواتساب أو البريد الإلكتروني",
    contactWhatsApp: "الدعم عبر الواتساب",
    contactEmail: "راسلنا بالبريد",
    conditionsTitle: "شروط الالتحاق",
    conditionsContent: [
      "الالتزام بالحضور المستمر في الحلقات المحددة.",
      "التقيد بآداب طالب العلم والوائح الخاصة بالنادي.",
      "إتمام مهام التلاوة المقررة في الوقت المحدد.",
      "المشاركة الفعالة في أنشطة النادي المختلفة والبرامج التعليمية."
    ],
    aboutContent: "مسك هو أحد الأندية الطلابية بجامعة السلطان قابوس، تشرف عليه عمادة شؤون الطلاب. يهدف إلى إعداد جيل يتلو القرآن الكريم بإتقان ويتقن أحكامه من خلال برامج تعليمية متخصصة.",
  }
};
